swagger: "2.0"
info:
  description: ""
  version: "1.0"
  title: "Booking API"
basePath: "/"
schemes:
  - "https"
paths:
  /availablility:
    get:
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: ""
          required: true
          schema:
            $ref: "#/definitions/availablilityRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/availablilityResponse"
  /booking:
    post:
      consumes: 
        - "application/json"
      produces: 
        - "application/json"
      parameters: 
        - in: "body"
          name: "body"
          description: ""
          required: true
          schema: 
            $ref: "#/definitions/bookingRequest"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/bookingResponse"

definitions:
  serviceTimeSlot:
    type: "object"
    required: 
      - merchantId
      - serviceId
      - start_time
    properties:
      merchantId: 
        type: "string"
      serviceId:
        type: "string"
      start_time:
        type: "string"
        format: "date-time"
      duration: 
        type: "integer"
        
  user:
    type: "object"
    required:
      - firstName
      - lastName
      - phoneNumber
      - email
    properties:
      firstName:
        type: "string"
      lastName:
        type: "string"
      phoneNumber:
        type: "string"
      email:
        type: "string"
        
  bookingRequest:
    type: "object"
    required: 
      - user
      - timeSlot
    properties:
      user:
        $ref: "#/definitions/user"
      timeSlot:
        $ref: "#/definitions/serviceTimeSlot"
      notes:
        type: "string"
  
  bookingResponse:
    type: "object"
    required: 
      - status
    properties:
      status:
        type: "string"
        enum: 
        - "booked"
        - "failed"
      merchantPhoneNumber:
        type: "string"
      confirmationId:
        type: "string"
      failureMessage:
        type: "string"
  
  availablilityRequest:
    type: "object"
    required: 
      - timeSlot
    properties:
      timeSlot: 
        $ref: "#/definitions/serviceTimeSlot"
        
  availablilityResponse:
    type: "object"
    properties:
      availability:
        type: "string"
        enum: 
        - "available"
        - "unavailable"
